### ISSUE TITLE
CircleCI can't connect to Postgres

### ISSUE THREAD

**Issue by lognaturel** [nafundi/jubilant-garbanzo#49]
When running tests:
```
node -e 'const { withDatabase, migrate } = require("./lib/model/database"); withDatabase(migrate);'
Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```
I think postgres just isn't started.

**Comment by clint-tseng** [comment]
Circle CI is particular about how postgres is run; you can't just spin it up at will. I'm not going to bother with CI until the integration tests are in.
